# Generated by Django 2.2.1 on 2019-06-05 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20190604_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
