# Generated by Django 2.2.1 on 2019-05-30 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='creditcard',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000000000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
